# Generated by Django 4.1.3 on 2023-02-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0002_rename_name_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task1',
        ),
    ]
