# Generated by Django 4.1.3 on 2023-02-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0003_rename_task_task_task1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task1',
            new_name='task',
        ),
    ]
