# Generated by Django 4.1.3 on 2023-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo1app', '0004_rename_task1_task_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-02-23'),
            preserve_default=False,
        ),
    ]
